# Generated by Django 4.2.2 on 2023-06-23 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("descricao", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Arte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("imagem", models.ImageField(upload_to="image/")),
                ("descricao", models.CharField(blank=True, max_length=200)),
                ("preco", models.IntegerField(null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arte.categoria",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="like_arte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salvo",
                    models.ManyToManyField(
                        blank=True,
                        related_name="salvar_arte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
