# Generated by Django 4.2.2 on 2023-06-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arte", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arte",
            name="slug",
        ),
        migrations.AlterField(
            model_name="arte",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="image/"),
        ),
    ]
