# Generated by Django 4.2.2 on 2023-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arte", "0002_remove_arte_slug_alter_arte_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arte",
            name="imagem",
            field=models.FileField(upload_to="image/"),
        ),
    ]
