# Generated by Django 4.2.2 on 2023-06-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arte", "0006_alter_arte_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=15)),
                ("comentario", models.TextField(max_length=300)),
                ("criado_em", models.TimeField(auto_now_add=True)),
                (
                    "arte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="arte.arte",
                    ),
                ),
            ],
            options={
                "ordering": ["criado_em"],
            },
        ),
    ]
