# Generated by Django 4.2.2 on 2023-07-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arte", "0007_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arte",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="image/"),
        ),
    ]
